### Endpoint to reset a user's password.
# Description:
# - This endpoint is used to reset the password of a user account.
# - The `{email}` path variable represents the email address associated with the user account for which the password reset is requested.
# - The `X-Requesting-App` header is required and must identify the application initiating the request.
# - Upon successful validation, the password reset process can proceed.


# Endpoint URL:
# - Production: https://milkyway.local:8555/andromeda-authorization-server/api/v1/public/account/reset-password/{email}
# - Localhost (for testing): http://localhost:8443/api/v1/public/account/reset-password/testuser3@example.com

PATCH http://localhost:8443/api/v1/public/account/reset-password/testuser3@example.com
Content-Type: application/json
X-Requesting-App: nebula_rest_api
