### Endpoint to change a user's password.
# Description:
# - This endpoint is used to change the password of an existing user account.
# - A valid `Authorization` Bearer token is required to ensure the request is authenticated.
# - The `X-Requesting-App` header must identify the application initiating the request.
# - The request body must include the following fields:
#     - `userId` (long): The unique identifier of the user.
#     - `email` (String): The email address associated with the user account.
#     - `actualPassword` (String): The current password of the user, hashed using bcrypt.
#     - `newPassword` (String): The new password for the user account.
# - This operation verifies the current password (`actualPassword`) before applying the change.
# - The new password is saved after being securely hashed.


# Endpoint URL:
# - Production: https://milkyway.local:8555/andromeda-authorization-server/api/v1/account/change-password
# - Localhost (for testing): http://localhost:8443/api/v1/account/change-password

POST http://localhost:8443/api/v1/account/change-password
Content-Type: application/json
X-Requesting-App: nebula_rest_api
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMDExLHhic212dXpmYXl5emp4ZHhha0Bja3B0ci5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifSx7ImlkIjo0LCJuYW1lIjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQzODU2MTM0LCJleHAiOjE3NDM4NTk3MzR9.gGTtabJ9um-txPp_vBE8V_plpyTuxMFRD36HPrcsDR_WVgj6lcnH2ykleBAz4myd_wQY05M6_GrwJw_WxKr3bA

{
  "userId": 998877,
  "email": "testuser-not-exist@example.com",
  "actualPassword": "cStbkrsp}B3VxD.",
  "newPassword": "password1234"
}

