GET https://localhost:8081/api/v1/nationalities/2

# public endpoint
# Examples
# GET https://milkyway.local:8555/nebula-rest-api/api/v1/nationalities/2
# GET http://localhost:8081/api/v1/nationalities/2
