GET https://localhost:8081/api/v1/users/achievements/1000011/1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMDExLHhic212dXpmYXl5emp4ZHhha0Bja3B0ci5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifSx7ImlkIjo0LCJuYW1lIjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ1NzYyNTY4LCJleHAiOjE3NDU3NjYxNjh9.9gXCWvmNtLe2tYd1gwEOf6fiAUm8ETRJxEbpjvxUNHK38wSm3em4wRSsTCGqCs3OKk_M16HCnleATFDc464FeA

# requires cookie with valid accessToken
# Examples
# GET https://milkyway.local:8555/nebula-rest-api/api/v1/users/achievements/10011/1
# GET http://localhost:8081/api/v1/users/achievements/{userId}/{achievementId}
