GET https://localhost:8081/api/v1/users/achievements?page=0&size=10&sortBy=achievementId&sortOrder=ASC&level=1&
    filterType=equal
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMDExLHhic212dXpmYXl5emp4ZHhha0Bja3B0ci5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifSx7ImlkIjo0LCJuYW1lIjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ1NzYwNDk4LCJleHAiOjE3NDU3NjQwOTh9.GFKm7e3NjP5q4ml_6lHaZI8yLCyi9E9CJ9zcEZN3T2VY4oCvL06b3IzpwsA6CJdnX4Dpe_xRKcnhNaTM5VGjvg

# requires cookie with valid accessToken
# Examples
# GET https://milkyway.local:8555/nebula-rest-api/api/v1/users/achievements?page=0&size=10&sortBy=achievementId&sortOrder=ASC&level=5&filterType=equal
# GET http://localhost:8081/api/v1/users/achievements?page=0&size=10&sortBy=achievementId&sortOrder=ASC&level=5&filterType=equal

# Example query parameters:
# page=0                        : number of page to return
# size=10                       : page size to return
# sortBy=achievementId          : Field to sort results, e.g., achievementId (default)
# sortOrder=asc                 : Sorting order: asc (ascending) or desc (descending, optional defaults to asc)
# level=1                       : achievementr level value filter
# filterType=less%20or%20equal  : level filter types: equal, less than, less or equal, greater, greater or equal
