### Endpoint for refresh access token.
# Description:
# - This endpoint is used to generate new accessToken based on current refreshToken.
# - The refreshToken must be provided in cookie.
# - Ensure that the `X-Requesting-App` header identifies the application making the request.
# - A successful response will contain an authentication token (e.g., JWT) in the response body.

# Endpoint URL:
# - Production: https://milkyway.local:8555/andromeda-authorization-server/api/v1/auth/refresh-access
# - Localhost: http://localhost:8443/api/v1/auth/refresh-access

POST https://milkyway.local:8555/andromeda-authorization-server/api/v1/auth/refresh-access
Content-Type: application/json
X-Requesting-App: nebula_rest_api
Cookie: refreshToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDAwMDExLHhic212dXpmYXl5emp4ZHhha0Bja3B0ci5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifSx7ImlkIjo0LCJuYW1lIjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ2MjY3NDg4LCJleHAiOjE3NDg4NTk0ODh9.vohJv_OODIQ7uSMPoHSOutLrPSVO1OyMi_7Eg32PFPfFzPLOxcnrqm6BV-bI_1WSBKJBOuc5m65aMRSSM019uw
