GET https://localhost:8081/api/v1/games/18

# public endpoint, return games
# Examples
# GET https://milkyway.local:8555/nebula-rest-api/api/v1/games/enabled
# GET http://localhost:8081/api/v1/games/enabled
