PATCH https://localhost:8081/api/v1/account/unlock/1000025
Content-Type: application/json

# used to unlock account process, should return body with success and "type": "VERIFICATION_MAIL_FROM_UNLOCK"
# Examples
# PATCH https://milkyway.local:8555/nebula-rest-api/api/v1/account/unlock/{id}
# PATCH http://localhost:8081/api/v1/account/unlock/1000025
