PATCH https://localhost:8081/api/v1/account/reset-password/nebulaTest1744652244148@nebula.com
Content-Type: application/json

# used to run reset password process, should return body with success and "type": "MAIL_NEW_PASSWD_SENT"
# Examples
# PATCH https://milkyway.local:8555/nebula-rest-api/api/v1/account/reset-password/{email}
# PATCH http://localhost:8081/api/v1/account/reset-password/nebulaTest1744652244148@nebula.com
