POST https://localhost:8081/api/v1/account/change-password
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNSxjbnk2ODI5MkBiY29vcS5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifV0sImlhdCI6MTc0NjE4NDIzMywiZXhwIjoxNzQ2MTg3ODMzfQ.y-0EI8jArnKa-CHw_4hgeIjl2NzXBviX44sQt7_jD0vHgp0_yI4r7pkpiqEkAdhXTLnfiEMprOEUGbtdNFgzPA

# used to change user password on request, requiers valid cookie accessToken (JWT Token)
# Examples
# POST https://milkyway.local:8555/nebula-rest-api/api/v1/account/change-password
# POST http://localhost:8081/api/v1/account/change-password

{
  "userId": 15,
  "email": "cny68292@bcooq.com",
  "actualPassword": "test001",
  "newPassword": "test001"
}
