PATCH https://localhost:8081/api/v1/users/profile
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNSxjbnk2ODI5MkBiY29vcS5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifSx7ImlkIjo0LCJuYW1lIjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzQ2MTg2MzE4LCJleHAiOjE3NDYxODk5MTh9.34qFvwcHwGw9kF2G-N5TLuMmzXevBan1wLETNsBcxmqs52KWdmzJn-_3IM321B7BbThajim4UygTtKTGFftFeQ

# used to update user profile data stoerd in nebula database,
# requires header: Content-Type: application/json
# Examples
# PATCH https://milkyway.local:8555/nebula-rest-api/api/v1/users/profile
# PATCH http://localhost:8081/api/v1/users/profile

{
  "userId": 15,
  "firstName": "Ralf",
  "lastName": "Blue",
  "birthdate": "1986-01-26T11:10:25.723Z",
  "nationalityId": 100,
  "genderId": 2
}
