PUT https://localhost:8081/api/v1/users/settings
Content-Type: application/json
Cookie: jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNSxjbnk2ODI5MkBiY29vcS5jb20iLCJpc3MiOiJEYkNvbm5lY3Rpb25BcHAiLCJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIifV0sImlhdCI6MTczNzg4OTY2NCwiZXhwIjoxNzM3ODkzMjY0fQ.wrXldmPatEKxXR8gCAUW7quQAcO-mTzWwADbwBEwtag1m-ZBiUSlRsAYag1jTtb2rSxSEqzJL70szdTGPOerBw

# used to update user settings data stoerd in nebula database,
# requires header: Content-Type: application/json
# Examples
# PUT https://milkyway.local:8555/nebula-rest-api/api/v1/users/settings
# PUT http://localhost:8081/api/v1/users/settings

{
  "userId": 15,
  "general": {
    "userId": 15,
    "theme": {
      "id": 2,
      "name": "fire"
    }

  },
  "sound": {
    "userId": 15,
    "muted": false,
    "battleCry": true,
    "volumeMaster": 80,
    "volumeMusic": 90,
    "volumeEffects": 70,
    "volumeVoices": 40
  }
}
